config/routes.rb
Rails.application.routes.draw do
  get "manifests/view_manifest" => "manifests#view_manifest"
  get "manifests/download" => "manifests#download"
  resources :manifests
  resources :orders
  devise_for :users
  resources :consignees
  resources :shippers
  root "welcome#index"

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :shipper
  belongs_to :consignee
  validates_uniqueness_of :hawb_number
end

app/controllers/orders_controller.rb
require 'json'

class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all.order('hawb_number DESC').paginate(:page => params[:page], per_page: 6)
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    @order.hawb_number = Hawb.first.number + 1

    @order.baggage_data = JSON.parse(order_params[:baggage_data])

    print eval(@order.baggage_data["1"]).class

    respond_to do |format|
      if @order.save
        Hawb.first.update(number: @order.hawb_number)
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    @order.baggage_data = eval(order_params[:baggage_data])
    print order_params[:baggage_data]
    respond_to do |format|
      if @order.update(order_params)
        @order.update(baggage_data: eval(order_params[:baggage_data]))
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add
    print "Saleem"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:hawb_number, :shipper_id, :consignee_id, :total_pieces, :total_weight, :items_cost, :content, :baggage_data)
    end
end

app/helpers/orders_helper.rb
require 'json'
module OrdersHelper
	def to_hash(value)
		val = eval(value)
		return val
	end
end

app/views/orders/_form.html.erb
<div class="row">
  <div class="col-lg-12">
    How many packages? <input type =  "number" id = "noOfFields" class = "form-control" required onkeypress = "return isNumberKey(event)" /><br/>
    <button class="btn btn-info" id="addField" data-remote="true">Add packages</button><br/><br/>
    <div class="row" id = "frm">
      <!-- <form class="form-horizontal" id="fields">
        
      </form> -->
    </div>
    <br/>
    <div class = "row" id = "createBtn">
      <input type = "button" id = "createPackagesBtn" class = "btn btn-primary" value = "Create Packages" style="display:none"/>
    </div>
    <div id = "showResults">
      <div class = "row" id = "results" style="display:none">
      </div>
    </div>
  </div>
</div>

<br/>

<%= simple_form_for(@order) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.label :shipper, "Shipper " %>
    <%= f.association :shipper, include_blank: true, input_html: { class: 'chosen-select' }, label: false %><br/>
    or
    <%= link_to "Create new Shipper", new_shipper_path, class: "btn btn-primary" %><br/><br/>
    <%= f.label :consignee, "Consignee" %>
    <%= f.association :consignee, include_blank: true, input_html: { class: 'chosen-select' }, label: false %><br/>
    or
    <%= link_to "Create new Consignee", new_consignee_path, class: "btn btn-primary" %><br/>
    <%= f.hidden_field :baggage_data %>
    <%= f.input :total_pieces %>
    <%= f.input :total_weight %>
    <%= f.input :items_cost %>
    <%= f.input :content %>
  </div>

  <div class="form-actions">
    <%= f.button :submit ,class: "btn btn-success" %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<div class="container">
	<h1>Editing Order</h1>
	<div class="row">
		<div class="col-lg-8">
			<%= render 'form' %>
		</div>
	</div>

	<br/>
	<div class="row">
		<%= link_to 'Show', @order, class: "btn btn-primary" %> |
		<%= link_to 'Back', orders_path, class: "btn btn-info" %>
	</div>
</div>

app/views/orders/index.html.erb
<div class="container">
  <% if notice.present? %>
    <div class="alert alert-info" role="alert">
      <p id="notice"><%= notice %></p>
    </div>
  <% end %>
  <div class="panel panel-primary">
    <div class="panel-heading">Listing Orders</div>

    <table class="table">
      <thead>
        <tr>
          <th>Hawb number</th>
          <th>Shipper</th>
          <th>Consignee</th>
          <th>Total pieces</th>
          <th>Total weight</th>
          <th>Items cost</th>
          <th>Content</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @orders.each do |order| %>
          <tr>
            <td><%= order.hawb_number %></td>
            <td><%= order.shipper.name %></td>
            <td><%= order.consignee.name %></td>
            <td><%= order.total_pieces %></td>
            <td><%= order.total_weight %></td>
            <td><%= order.items_cost %></td>
            <td><%= order.content %></td>
            <td><%= link_to 'Show', order, class: "btn btn-primary" %></td>
            <td><%= link_to 'Edit', edit_order_path(order), class: "btn btn-warning" %></td>
            <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="digg_pagination">
    <center>   <%= will_paginate @orders, renderer: BootstrapPagination::Rails %> </center>
  </div>
  <br>
  <%= link_to 'New Order', new_order_path, class: "btn btn-primary" %>
</div>

app/views/orders/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-10">
			<h1>New Order</h1>

			<%= render 'form' %>
			<br/>
			<%= link_to 'Back', orders_path, class: "btn btn-primary" %>
		</div>
		<div class="col-lg-2">
		</div>
	</div>
</div>

app/views/orders/show.html.erb
<div class="container">
<div class="row">
  <% if notice.present? %>
    <div class="alert alert-info" role="alert">
      <p id="notice"><%= notice %></p>
    </div>
  <% end %>
  <div class="col-lg-10">
  <div class="panel panel-primary">

  <div class="panel-heading"><h2>Orders</h2></div>
    <div class="list-group">

      <div class="list-group-item">

        <p>
          <strong>Hawb number:</strong>
          <%= @order.hawb_number %>
        </p>
        </div>

            <div class="list-group-item">

        <p>
          <strong>Shipper:</strong>
          <%= @order.shipper.name %>
        </p>
        </div>

            <div class="list-group-item">

        <p>
          <strong>Consignee:</strong>
          <%= @order.consignee.name %>
        </p>
        </div>

            <div class="list-group-item">

        <p>
          <strong>Total pieces:</strong>
          <%= @order.total_pieces %>
        </p>
        </div>

        <div class="list-group-item">
        <p>
          <strong>Total weight:</strong>
          <%= @order.total_weight %>
        </p>
        </div>

        <div class="list-group-item">
        <ul>
        <p> <strong>Dimensions</strong>
        <% if @order.baggage_data %>
         <% @order.baggage_data.each do |key, value| %>
          <ul> <%= key %> :
           <% val = to_hash(value) %>
           <% val.each do |k,v| %>
            <li><%= k.humanize %> : <%= v %></li>
           <% end %>
          </ul>
         <% end %>
        <% end %>
        </ul>
        </div>

            <div class="list-group-item">
        <p>
          <strong>Items cost:</strong>
          <%= @order.items_cost %>
        </p>
        </div>

            <div class="list-group-item">
        <p>
          <strong>Content:</strong>
          <%= @order.content %>
        </p>
        </div>
    </div>
    </div>
  </div>
</div>
<%= link_to 'Edit', edit_order_path(@order), class: "btn btn-warning" %> |
<%= link_to 'Back', orders_path, class: "btn btn-primary" %>
</div>