config/routes.rb
Rails.application.routes.draw do
  get "manifests/view_manifest" => "manifests#view_manifest"
  get "manifests/download" => "manifests#download"
  resources :manifests
  resources :orders
  devise_for :users
  resources :consignees
  resources :shippers
  root "welcome#index"

end

app/models/manifest.rb
class Manifest < ActiveRecord::Base
  belongs_to :order
  # alidates_presence_of :mawb, :order_id
  def self.search(query)
  	if query
  		return Manifest.all.where(mawb: query)
  	else
  		return Manifest.all
  	end
  end
end

app/controllers/manifests_controller.rb
class ManifestsController < ApplicationController
  before_action :set_manifest, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /manifests
  # GET /manifests.json
  def index
    if params[:search].present?
      result = Manifest.search(params[:search])
      @manifests = result.paginate(page: params[:page], per_page: 10)
    else
      @manifests = Manifest.paginate(page: params[:page], per_page: 10)
    end
  end

  # GET /manifests/1
  # GET /manifests/1.json
  def show
  end

  # GET /manifests/new
  def new
    @manifest = Manifest.new
  end

  # GET /manifests/1/edit
  def edit
  end

  # POST /manifests
  # POST /manifests.json
  def create
    @manifest = Manifest.new(manifest_params)
    #print manifest_params[:order_id]
    order_array = []
    hawb_number_array = []
    orders_to_update = []

    for i in 0..manifest_params[:order_id].length-2
      order_array.push(manifest_params[:order_id][i].to_i)
    end

    orders = Order.find(order_array)
    # print orders.first.hawb_number
    orders.each do |o|
      hawb_number_array.push(o.hawb_number.to_s)
      orders_to_update.push(o.id)
    end

    @manifest.orders_to_manifest = order_array
    @manifest.hawb_numbers_to_manifest = hawb_number_array

    respond_to do |format|
      if @manifest.save
        orders_to_update.each do |otu|
          order = Order.find(otu)
          order.update(manifested_flag: true)
        end
        format.html { redirect_to @manifest, notice: 'Manifest was successfully created.' }
        format.json { render :show, status: :created, location: @manifest }
      else
        format.html { render :new }
        format.json { render json: @manifest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /manifests/1
  # PATCH/PUT /manifests/1.json
  def update
    order_array = []
    hawb_number_array = []
    for i in 0..manifest_params[:order_id].length-2
      order_array.push(manifest_params[:order_id][i].to_i)
    end

    orders = Order.find(order_array)
    
    orders.each do |o|
      hawb_number_array.push(o.hawb_number.to_s)
    end

    @manifest.orders_to_manifest = order_array
    @manifest.hawb_numbers_to_manifest = hawb_number_array
    
    respond_to do |format|
      if @manifest.update(manifest_params)
        format.html { redirect_to @manifest, notice: 'Manifest was successfully updated.' }
        format.json { render :show, status: :ok, location: @manifest }
      else
        format.html { render :edit }
        format.json { render json: @manifest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /manifests/1
  # DELETE /manifests/1.json
  def destroy
    @manifest.destroy
    respond_to do |format|
      format.html { redirect_to manifests_url, notice: 'Manifest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def view_manifest
    mawb = manifest_params[:mawb]
    @manifest = Manifest.find_by(mawb: mawb)
    orders_to_manifest = @manifest.orders_to_manifest
    @orders = Order.find(orders_to_manifest)
    remaing_weight = 0
    remaining_weight_baggage = {}
    last_baggage_number = 0
    baggage_list = {}

    flag = true

    @orders.each do |o|
      pieces_array = [] 
      single_piece_detail = {}
      last_baggage_number += 1
      decimal = 0
      pieces = o.total_weight/30
      s_pieces = pieces.floor
      puts "Pieces: " + s_pieces.to_s
      
      start = last_baggage_number
      last_baggage_number = s_pieces + start -1

      # puts "remaing_weight: " + remaing_weight.ceil.to_s
      # puts "Order total weight: " + o.total_weight.to_s
    
      # puts "start: " + start.to_s
      # puts "last_baggage_number: " + last_baggage_number.to_s
      for i in start.to_i..last_baggage_number.to_i
        single_piece_detail[i.to_s] = 30
      end

      # pieces_array.push(single_piece_detail)
      # print "saleem"

      if pieces % 1 != 0
        puts "Pieces dec: " + pieces.to_s
        decimal = pieces - pieces.floor
        # puts "Decimal: " + decimal.to_s
        remaing_weight = (decimal * 30)

        puts "Balance: " + remaing_weight.to_s

        remaining_weight_baggage.each do |k,v|

          weight = v.to_i + remaing_weight

          # puts "Weight: "+weight.round.to_s
          

          if weight.to_i <= 32
            # puts k.to_s
            # puts remaing_weight
            # puts v.to_i
            if v.to_i > 2
              single_piece_detail[k.to_s] = remaing_weight.to_i
              remaining_weight_baggage[k.to_s] = v - remaing_weight
              puts "Remaining Weight baggage: " + remaining_weight_baggage[k.to_s].to_s 
              # puts "remaing_weight: " + (remaing_weight - v).to_s
              flag = false
            end
          end
        end

        remaining_weight_baggage.each do |r,vv|
          puts r.to_s + ":" + vv.to_s
        end

        if flag
          last_baggage_number += 1
          remaining_weight_baggage[last_baggage_number.to_i.to_s] = remaing_weight
          single_piece_detail[last_baggage_number.to_s] = remaing_weight.to_i
          pieces += 1
        end
        flag = true
      end
      # pieces_array.push(single_piece_detail)
      # puts pieces_array
      
      baggage_list[o.hawb_number.to_s] = single_piece_detail
      # baggage_list = single_piece_detail
      # remain
    end

    puts baggage_list

    @baggages = baggage_list
    # puts remaining_weight_baggage
    # puts "pieces_array:"
    # puts pieces_array
    # return [@orders,@manifest,@baggages]
    clr = caller[0][/`.*'/][1..-2]
    if clr == "block (2 levels) in download"
      return
    else 
      respond_to do |format|
        format.html
        format.pdf do
          render pdf: "Manifest",
                template: 'manifests/view_manifest.pdf.erb',
                layout: 'pdf.html.erb',
               margin:  {   top:               5,                     # default 10 (mm)
                            bottom:            10,
                            left:              10,
                            right:             10 }  # Excluding ".pdf" extension.
        end
      end
    end
    
  end


  def download
    respond_to do |format|
      format.xlsx do
        render xslx: view_manifest, filename: "Manifest_#{@manifest.mawb}"
      end
    end
  end

  # def download_xls
  #   respond_to do |format|
  #     format.html
  #     format.xlsx { render xlsx: :index, filename: "my_items_doc" }
  #   end
  # end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_manifest
      @manifest = Manifest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def manifest_params
      params.require(:manifest).permit(:mawb, { :order_id => [] } )
    end
end

app/helpers/manifests_helper.rb
module ManifestsHelper
	def to_upcase(word)
		return word.upcase
	end
	def to_string(number)
		return number.to_s
	end
	def orders_not_manifested_yet
		return Order.all.where(manifested_flag: false)
	end
	def to_hash(value)
		val = eval(value)
		return val
	end
end

app/views/manifests/_form.html.erb
<%= simple_form_for(@manifest) do |f| %>
  <%= f.error_notification %>
  <% if orders_not_manifested_yet.count == 0 %>
    <div class="alert alert-info" role="alert">
      <p id="notice">Looks like all the orders have been manifested.</p><br/>
      <%= link_to "Create a new Order",new_order_path, class: "btn btn-primary" %>
    </div>
  <% else %>
	<div class="form-inputs">
	  <%= f.input :mawb %>
	  <%= f.association :order, as: :check_boxes, collection: orders_not_manifested_yet.order(:id), :label_method => lambda { |order| "#{order.hawb_number}" }%>   
	</div>
	<div class="form-actions">
	   <%= f.button :submit, class: "btn btn-success" %>
	</div>
  <% end %>
<% end %>

app/views/manifests/download.xlsx.erb
<div class="container">
	<div class="row">
		<div class="col-lg-2">
		</div>
		<div class="col-lg-8">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3>MAWB: <%= @manifest.mawb %></h3>
				</div>
				<!-- <div class="panel-body">
					<h3><a href="/manifests/download.pdf?manifest[mawb]=<%= @manifest.mawb %>">Download Manifest</a></h3>
				</div> -->
				<table class="table">
					<thead>
						<tr>
							<th>HAWB NO</th>
							<th>Shipper</th>
							<th>Consignee</th>
							<th>Pieces</th>
							<th>Bag Weight</th>
							<th>Content</th>
							<th>AED</th>
						</tr>
					</thead>

					<tbody>
						<% @orders.each do |order| %>
							<tr>
								<td>
									<%= order.hawb_number %><br/>
									
									<% @baggages.each do |baggage,i| %>
										<% if baggage == order.hawb_number.to_s %>
											<% i.each do |k,v| %>
												<!-- <h5>Bag No<%= k %>: <%= v %></h5> -->
												<%= k %>
											<% end %>
										<% end %>
									<% end %>
								</td>
								<td>
									<strong><%= order.shipper.name %></strong><br/>
									<%= order.shipper.address_line_1 %><br/>
									<h5>TEL: </h5><%= order.shipper.tel_no %>
								</td>
								<td>
									<strong><%= order.consignee.name %></strong><br/>
									<%= order.consignee.address_line_1 %><br/>
									<h5>TEL: </h5><%= order.consignee.tel_no_1 %>
								</td>
								<td><%= order.total_pieces %></td>
								<td><%= order.total_weight %></td>
								<td><%= order.content %></td>
								<td><%= order.items_cost %></td>
							</tr>
						<% end %>
					</tbody>
				</table>
			</div>
		</div>
		<div class="col-lg-2">
		</div>
	</div>
</div>

app/views/manifests/edit.html.erb
<div class="container">
	<h1>Editing Manifest</h1>
	<div class="row">
		<div class="col-lg-8">
			<%= render 'form' %>
		</div>
	</div>

	<br/>
	<div class="row">
		<%= link_to 'Show', @manifest, class: "btn btn-primary" %> |
		<%= link_to 'Back', manifests_path, class: "btn btn-info" %>
	</div>
</div>

app/views/manifests/index.html.erb
<div class="container">
  <% if notice.present? %>
    <div class="alert alert-info" role="alert">
      <p id="notice"><%= notice %></p>
    </div>
  <% end %>
  
  <div class="panel panel-primary">
    <div class="panel-heading">Listing Manifests</div>
    <div class="panel-body">
      <form action="/manifests" method = "get">
        <div class="col-md-4">
          <input type="text" name="search" class="form-control" />
        </div>
        <input type="submit" value="Submit" class="btn btn-success" />
      </form>
    </div>
    
      <table class="table"> 
        <thead>
          <tr>
            <th>MAWB</th>
            <th>Download link</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @manifests.each do |manifest| %>
            <tr>
              <td><%= manifest.mawb %></td>
              <td><h5><a href="/manifests/view_manifest.pdf?manifest[mawb]=<%= manifest.mawb %>">PDF</a> | <a href="/manifests/download.xlsx?manifest[mawb]=<%= manifest.mawb %>"> EXCEL</a></h5></td>
              <td><%= link_to 'Show', manifest, class: "btn btn-primary" %></td>
              <td><%= link_to 'Edit', edit_manifest_path(manifest), class: "btn btn-warning" %></td>
              <td><%= link_to 'Destroy', manifest, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
  </div>
  <div class="digg_pagination">
    <center>   <%= will_paginate @manifests, renderer: BootstrapPagination::Rails %> </center>
  </div>
  <br>
<br>

<%= link_to 'New Manifest', new_manifest_path, class: "btn btn-info" %>
</div>

app/views/manifests/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-log-2">
		</div>
		<div class="col-lg-8">
			<h1>New Manifest</h1>

			<%= render 'form' %>
			<br/>
			<%= link_to 'Back', manifests_path, class: "btn btn-primary" %>
		</div>
		<div class="col-lg-2">
		</div>
	</div>
</div>

app/views/manifests/show.html.erb
<div class="container">
<div class="row">
  <% if notice.present? %>
    <div class="alert alert-info" role="alert">
      <p id="notice"><%= notice %></p>
    </div>
  <% end %>
  <div class="col-lg-10">
  <div class="panel panel-primary">

  <div class="panel-heading"><h2>Manifests</h2></div>
    <div class="list-group">

      <div class="list-group-item">
		<p>
		  <strong>MAWB:</strong>
		  <%= @manifest.mawb %>
		</p>
		</div>

        <div class="list-group-item">
		<p>
		  <strong>Orders to manifest:</strong>
		  <ul>
		  <% @manifest.hawb_numbers_to_manifest.each do |hawb|%>
		  	<li><%= hawb %></li>
		  <% end %>
		  </ul>
		</p>
		</div>

		<div class="list-group-item">
			<h4><a href="/manifests/view_manifest?manifest[mawb]=<%= @manifest.mawb %>">Show Manifest</a></h4>
		</div>
		</div>
    </div>
  </div>
</div>

<%= link_to 'Edit', edit_manifest_path(@manifest), class: "btn btn-warning" %> |
<%= link_to 'Back', manifests_path, class: "btn btn-primary" %>
</div>

app/views/manifests/view_manifest.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-2">
		</div>
		<div class="col-lg-8">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3>MAWB: <%= @manifest.mawb %></h3>
				</div>
				<!-- <div class="panel-body">
					<h3><a href="/manifests/download.pdf?manifest[mawb]=<%= @manifest.mawb %>">Download Manifest</a></h3>
				</div> -->
				<div class="table-responsive">
				<table class="table">
					<thead>
						<tr>
							<th>HAWB NO</th>
							<th>Shipper</th>
							<th>Consignee</th>
							<th>Pieces</th>
							<th>Bag Weight</th>
							<th>Content</th>
							<th>AED</th>
						</tr>
					</thead>

					<tbody>
						<% @orders.each do |order| %>
							<tr>
								<td class="col-md-3">
									<%= order.hawb_number %><br/>
									<% order.baggage_data.each do |baggage| %>
										<% h = to_hash(baggage[1]) %>
										<%= h["bag_number"] %>
									<% end %>
									<!-- 
									<% @baggages.each do |baggage,i| %>
										<% if baggage == order.hawb_number.to_s %>
											<% i.each do |k,v| %>
												 <h5>Bag No<%= k %>: <%= v %></h5> 
												<%= k %>
											<% end %>
										<% end %>
									<% end %>
									-->
								</td>
								<td class="col-md-3">
									<strong><%= order.shipper.name %></strong><br/>
									<%= order.shipper.address_line_1 %><br/>
									<h5>TEL: </h5><%= order.shipper.tel_no %>
								</td>
								<td class="col-md-3">
									<strong><%= order.consignee.name %></strong><br/>
									<%= order.consignee.address_line_1 %><br/>
									<h5>TEL: </h5><%= order.consignee.tel_no_1 %>
								</td>
								<td class="col-md-3"><%= order.total_pieces %></td>
								<td class="col-md-3"><%= order.total_weight %></td>
								<td class="col-md-2"><%= order.content %></td>
								<td class="col-md-3"><%= order.items_cost %></td>
							</tr>
						<% end %>
					</tbody>
				</table>
				</div>
			</div>
		</div>
		<div class="col-lg-2">
		</div>
	</div>
</div>

app/views/manifests/view_manifest.pdf.erb
<div class="container">
	<div class="row">
		<div class="col-lg-2">
		</div>
		<div class="col-lg-8">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3>MAWB: <%= @manifest.mawb %></h3>
				</div>
				<!-- <div class="panel-body">
					<h3><a href="/manifests/download.pdf?manifest[mawb]=<%= @manifest.mawb %>">Download Manifest</a></h3>
				</div> -->
				<table class="table">
					<thead>
						<tr>
							<th>HAWB NO</th>
							<th>Shipper</th>
							<th>Consignee</th>
							<th>Pieces</th>
							<th>Bag Weight</th>
							<th>Content</th>
							<th>AED</th>
						</tr>
					</thead>

					<tbody>
						<% @orders.each do |order| %>
							<tr>
								<td>
									<%= order.hawb_number %><br/>
									<% order.baggage_data.each do |baggage| %>
										<% h = to_hash(baggage[1]) %>
										<%= h["bag_number"] %>
									<% end %>
									<!-- 
									<% @baggages.each do |baggage,i| %>
										<% if baggage == order.hawb_number.to_s %>
											<% i.each do |k,v| %>
												 <h5>Bag No<%= k %>: <%= v %></h5> 
												<%= k %>
											<% end %>
										<% end %>
									<% end %>
									-->
								</td>
								<td>
									<strong><%= order.shipper.name %></strong><br/>
									<%= order.shipper.address_line_1 %><br/>
									<h5>TEL: </h5><%= order.shipper.tel_no %>
								</td>
								<td>
									<strong><%= order.consignee.name %></strong><br/>
									<%= order.consignee.address_line_1 %><br/>
									<h5>TEL: </h5><%= order.consignee.tel_no_1 %>
								</td>
								<td><%= order.total_pieces %></td>
								<td><%= order.total_weight %></td>
								<td><%= order.content %></td>
								<td><%= order.items_cost.round(2) %></td>
							</tr>
						<% end %>
					</tbody>
				</table>
			</div>
		</div>
		<div class="col-lg-2">
		</div>
	</div>
</div>

app/views/manifests/view_manifest.xlsx.erb
<div class="container">
	<div class="row">
		<div class="col-lg-2">
		</div>
		<div class="col-lg-8">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3>MAWB: <%= @manifest.mawb %></h3>
				</div>
				<!-- <div class="panel-body">
					<h3><a href="/manifests/download.pdf?manifest[mawb]=<%= @manifest.mawb %>">Download Manifest</a></h3>
				</div> -->
				<table class="table">
					<thead>
						<tr>
							<th>HAWB NO</th>
							<th>Shipper</th>
							<th>Consignee</th>
							<th>Pieces</th>
							<th>Bag Weight</th>
							<th>Content</th>
							<th>AED</th>
						</tr>
					</thead>

					<tbody>
						<% @orders.each do |order| %>
							<tr>
								<td class="col-md-3">
									<%= order.hawb_number %><br/>
									<% order.baggage_data.each do |baggage| %>
										<% h = to_hash(baggage[1]) %>
										<%= h["bag_number"] %>
									<% end %>
									<!-- 
									<% @baggages.each do |baggage,i| %>
										<% if baggage == order.hawb_number.to_s %>
											<% i.each do |k,v| %>
												 <h5>Bag No<%= k %>: <%= v %></h5> 
												<%= k %>
											<% end %>
										<% end %>
									<% end %>
									-->
								</td>
								<td class="col-md-3">
									<strong><%= order.shipper.name %></strong><br/>
									<%= order.shipper.address_line_1 %><br/>
									<h5>TEL: </h5><%= order.shipper.tel_no %>
								</td>
								<td class="col-md-3">
									<strong><%= order.consignee.name %></strong><br/>
									<%= order.consignee.address_line_1 %><br/>
									<h5>TEL: </h5><%= order.consignee.tel_no_1 %>
								</td>
								<td class="col-md-3"><%= order.total_pieces %></td>
								<td class="col-md-3"><%= order.total_weight %></td>
								<td class="col-md-3"><%= order.content %></td>
								<td class="col-md-3"><%= order.items_cost %></td>
							</tr>
						<% end %>
					</tbody>
				</table>
			</div>
		</div>
		<div class="col-lg-2">
		</div>
	</div>
</div>