config/routes.rb
Rails.application.routes.draw do
  get "manifests/view_manifest" => "manifests#view_manifest"
  get "manifests/download" => "manifests#download"
  resources :manifests
  resources :orders
  devise_for :users
  resources :consignees
  resources :shippers
  root "welcome#index"

end

app/models/consignee.rb
class Consignee < ActiveRecord::Base
	has_many :orders, dependent: :delete_all
	validates_uniqueness_of :po_box_no,:address_line_1, :email, :tel_no_1
	validates_format_of :email,:with => Devise::email_regexp
end

app/controllers/consignees_controller.rb
class ConsigneesController < ApplicationController
  before_action :set_consignee, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  $ref = false
  # GET /consignees
  # GET /consignees.json
  def index
    @consignees = Consignee.paginate(page: params[:page], per_page: 10)
  end

  # GET /consignees/1
  # GET /consignees/1.json
  def show
  end

  # GET /consignees/new
  def new
    @consignee = Consignee.new
    $ref = URI.parse(request.env["HTTP_REFERER"]).to_s.include?("orders")
  end

  # GET /consignees/1/edit
  def edit
  end

  # POST /consignees
  # POST /consignees.json
  def create
    @consignee = Consignee.new(consignee_params)

    respond_to do |format|
      if @consignee.save
        if $ref
          # redirect_to new_order_path
          format.html { redirect_to new_order_path, notice: 'Consignee was successfully created.' }
        else
          format.html { redirect_to @consignee, notice: 'Consignee was successfully created.' }
        end
        # format.html { redirect_to @consignee, notice: 'Consignee was successfully created.' }
        format.json { render :show, status: :created, location: @consignee }
      else
        format.html { render :new }
        format.json { render json: @consignee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /consignees/1
  # PATCH/PUT /consignees/1.json
  def update
    respond_to do |format|
      if @consignee.update(consignee_params)
        if $ref
          # redirect_to new_order_path
          format.html { redirect_to new_order_path, notice: 'Consignee was successfully created.' }
        else
          format.html { redirect_to @consignee, notice: 'Consignee was successfully created.' }
        end
        # format.html { redirect_to @consignee, notice: 'Consignee was successfully updated.' }
        format.json { render :show, status: :ok, location: @consignee }
      else
        format.html { render :edit }
        format.json { render json: @consignee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /consignees/1
  # DELETE /consignees/1.json
  def destroy
    @consignee.destroy
    respond_to do |format|
      format.html { redirect_to consignees_url, notice: 'Consignee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_consignee
      @consignee = Consignee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def consignee_params
      params.require(:consignee).permit(:name, :address_line_1, :address_line_2, :po_box_no, :city, :country, :tel_no_1, :tel_no_2, :email)
    end
end

app/helpers/consignees_helper.rb
module ConsigneesHelper
end

app/views/consignees/_form.html.erb
<%= simple_form_for(@consignee) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, required: true %>
    <%= f.input :address_line_1 %>
    <%= f.input :address_line_2 %>
    <%= f.input :po_box_no, required: true %>
    <%= f.input :city %>
    <%= f.input :country, required: true %>
    <%= f.input :tel_no_1, required: true %>
    <%= f.input :tel_no_2 %>
    <%= f.input :email %>
  </div>

  <div class="form-actions">
    <%= f.button :submit  ,class: "btn btn-success" %>
  </div>
<% end %>

app/views/consignees/edit.html.erb
<div class="container">
	<h1>Editing Consignee</h1>
	<div class="row">
		<div class="col-lg-8">
			<%= render 'form' %>
		</div>
	</div>
	<br/>
	<div class="row">
		<%= link_to 'Show', @consignee, class: "btn btn-primary" %> |
		<%= link_to 'Back', consignees_path, class: "btn btn-info" %>
	</div>

</div>

app/views/consignees/index.html.erb
<div class="container">
<% if notice.present? %>
  <div class="alert alert-info" role="alert">
    <p id="notice"><%= notice %></p>
  </div>
<% end %>
<div class="panel panel-primary">

<div class="panel-heading">Listing Consignees</div>

<table class="table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Address line 1</th>
      <th>Po box no</th>
      <th>Tel no 1</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @consignees.each do |consignee| %>
      <tr>
        <td><%= consignee.id %></td>
        <td><%= consignee.name %></td>
        <td><%= consignee.address_line_1 %></td>
        <td><%= consignee.po_box_no %></td>
        <td><%= consignee.tel_no_1 %></td>
        <td><%= consignee.email %></td>
        <td><%= link_to 'Show', consignee, class: "btn btn-primary" %></td>
        <td><%= link_to 'Edit', edit_consignee_path(consignee), class: "btn btn-warning" %></td>
        <td><%= link_to 'Destroy', consignee, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
      </tr>
     
    <% end %>
  </tbody>
</table>

</div>
<div class="digg_pagination">
    <center>   <%= will_paginate @consignees, renderer: BootstrapPagination::Rails %> </center>
  </div>
  <br>
<br>

<%= link_to 'New Consignee', new_consignee_path, class: "btn btn-primary" %>
</div>

app/views/consignees/new.html.erb
<div class="container">
	<h1>New Consignee</h1>
	<div class="row">
		<div class="col-lg-8">
			<%= render 'form' %>
		</div>
	</div>
	<br/>
	<div class="row">
		<%= link_to 'Back', consignees_path, class: "btn btn-primary" %>
	</div>
</div>

app/views/consignees/show.html.erb
<div class="container">
<div class="row">
  <% if notice.present? %>
  <div class="alert alert-info" role="alert">
    <p id="notice"><%= notice %></p>
  </div>
  <% end %>
<div class="col-lg-10">
<div class="panel panel-primary">


  <div class="panel-heading"><h2>Consignee</h2></div>
  <div class="list-group">

    <div class="list-group-item">
      <p>
        <strong>Name:</strong>
        <%= @consignee.name %>
      </p>
    </div>

    <div class="list-group-item">
        <strong>Address line 1:</strong>
        <%= @consignee.address_line_1 %>
    </div>
    <div class="list-group-item">
      <p>
        <strong>Address line 2:</strong>
        <%= @consignee.address_line_2 %>
      </p>
    </div>

    <div class="list-group-item">
      <p>
        <strong>Po box no:</strong>
        <%= @consignee.po_box_no %>
      </p>
    </div>

    <div class="list-group-item">
      <p>
        <strong>City:</strong>
        <%= @consignee.city %>
      </p>
    </div>

    <div class="list-group-item">
      <p>
        <strong>Country:</strong>
        <%= @consignee.country %>
      </p>
    </div>

    <div class="list-group-item">
      <p>
        <strong>Tel no 1:</strong>
        <%= @consignee.tel_no_1 %>
      </p>
    </div>

    <div class="list-group-item">
      <p>
        <strong>Tel no 2:</strong>
        <%= @consignee.tel_no_2 %>
      </p>
    </div>

    <div class="list-group-item">
      <p>
        <strong>Email:</strong>
        <%= @consignee.email %>
      </p>
    </div>
  </div>
</div>
</div>
</div>
<%= link_to 'Edit', edit_consignee_path(@consignee), class: "btn btn-warning" %> |
<%= link_to 'Back', consignees_path, class: "btn btn-primary" %>
</div>