config/routes.rb
Rails.application.routes.draw do
  get "manifests/view_manifest" => "manifests#view_manifest"
  get "manifests/download" => "manifests#download"
  resources :manifests
  resources :orders
  devise_for :users
  resources :consignees
  resources :shippers
  root "welcome#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NishaShipping</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Nisha Shipping</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="nav-item">
          <%= link_to "Shippers", shippers_path %>
        </li>
        <li class="nav-item">
          <%= link_to "Consignees", consignees_path %>
        </li>
        <li class="nav-item">
          <%= link_to "Orders", orders_path %>
        </li>
        <li class="nav-item">
          <%= link_to "Manifests", manifests_path %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">

        <% if !user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path %>
          </li>
        <% else %>
          
           <p class="navbar-text">Signed in as <strong><%= current_user.email %></strong></p>
            
          <li class="nav-item">
            <%= link_to "Edit", edit_user_registration_path %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
          </li>
        <% end %>   
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<%= yield %>
</body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
<head>
  <style type="text/css">
  	tr {
		page-break-inside: avoid;
	}
  </style>
  <title>PDF</title>
  <%= wicked_pdf_stylesheet_link_tag 'application', media: 'all','data-turbolinks-track' => true %>
</head>
<body>
  <div class='container'>
    <%= yield %>
  </div>

</body>
</html>